---
    - name: Install packages
      ansible.builtin.package:
        name:
          - zsh
          - tmux
          - git
          - fzf
          - fontconfig
        state: present
      become: true

    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh
      become: true

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: "/home/{{ user }}/install.sh"
        mode: '0755'

    - name: Check if oh-my-zsh is installed
      stat:
        path: "/home/{{ user }}/.oh-my-zsh"
      register: oh_my_zsh

    - name: Install ohmyzsh
      ansible.builtin.script:
        cmd: "/home/{{ user }}/install.sh"
      when: not oh_my_zsh.stat.exists

    - name: Install PowerLevel10K
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1

    - name: Check if Meslo NerdFonts is installed
      stat:
        path: "/home/{{ user }}/.local/fonts/Meslo"
      register: nerdfontMeslo

    - name: Download NerdFonts
      ansible.builtin.get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Meslo.zip
        dest: "/home/{{ user }}/Meslo.zip"

    - name: Create temp directory
      ansible.builtin.file:
        path: "/home/{{ user }}/Meslo"
        state: directory
        mode: '0755'

    - name: Create font install directory
      ansible.builtin.file:
        path: "/home/{{ user }}/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Install font files
      ansible.builtin.unarchive:
        src: "/home/{{ user }}/Meslo.zip"
        dest: "/home/{{ user }}/Meslo"

    - name: Move font files to fonts directory
      ansible.builtin.copy:
        src: "/home/{{ user }}/Meslo"
        dest: "/home/{{ user }}/.local/share/fonts/Meslo"

    - name: Update fonts cache
      ansible.builtin.command:
        cmd: fc-cache -f -v

    - name: Update .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.zshrc"
        insertafter: EOF
        line: "source /home/{{ user }}/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme"

    - name: Add .local/bin to path
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        insertafter: 'export ZSH=\$HOME/\.oh-my-zsh'
        line: "path+={{ ansible_env.HOME }}/.local/bin/"

    - name: create custom plugins directories
      ansible.builtin.file:
        path: "/home/{{ user }}/.oh-my-zsh/custom/plugins/krm"
        state: directory
        mode: '0755'

    - name: Install powerlevel10k config file
      ansible.builtin.template:
        src: "templates/p10k.zsh.j2"
        dest: "/home/{{ user }}/.p10k.zsh"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644
      tags:
        - debug

    - name: add custom plugin to oh-my-zsh
      ansible.builtin.template:
        src: "templates/krm.plugin.zsh.j2"
        dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/krm/krm.plugin.zsh"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: 0644

    - name: Add plugins fzf git krm ssh tmux web-search to zshrc
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: '^plugins=*'
        line: 'plugins=(fzf git krm ssh-agent sqn tmux web-search)'
